package net.subfx.arkplanner.js

/**
 * Engram models
 */

case class Engram(name: String, points: Int, reqLevel: Int, imageUrl: String, preReqs: List[Engram])

object Engrams {

  val levels: Map[Int, Int] = Map(
    1 -> 0,
    2 -> 8,
    3 -> 8,
    4 -> 8,
    5 -> 8,
    6 -> 8,
    7 -> 8,
    8 -> 8,
    9 -> 8,
    10 -> 12,
    11 -> 12,
    12 -> 12,
    13 -> 12,
    14 -> 12,
    15 -> 12,
    16 -> 12,
    17 -> 12,
    18 -> 12,
    19 -> 12,
    20 -> 16,
    21 -> 16,
    22 -> 16,
    23 -> 16,
    24 -> 16,
    25 -> 16,
    26 -> 16,
    27 -> 16,
    28 -> 16,
    29 -> 16,
    30 -> 20,
    31 -> 20,
    32 -> 20,
    33 -> 20,
    34 -> 20,
    35 -> 20,
    36 -> 20,
    37 -> 20,
    38 -> 20,
    39 -> 20,
    40 -> 24,
    41 -> 24,
    42 -> 24,
    43 -> 24,
    44 -> 24,
    45 -> 24,
    46 -> 24,
    47 -> 24,
    48 -> 24,
    49 -> 24,
    50 -> 28,
    51 -> 28,
    52 -> 28,
    53 -> 28,
    54 -> 28,
    55 -> 28,
    56 -> 28,
    57 -> 28,
    58 -> 28,
    59 -> 28,
    60 -> 40,
    61 -> 40,
    62 -> 40,
    63 -> 40,
    64 -> 40,
    65 -> 1
  )

  val table: List[Engram] = List(
    Engram("Campfire", 3, 2, "", Nil),
    Engram("Stone Hatchet", 3, 2, "", Nil),
    Engram("Spear", 3, 2, "", Nil),
    Engram("Note", 3, 2, "", Nil),
    Engram("Cloth Pants", 3, 2, "", Nil),
    Engram("Cloth Shirt", 3, 2, "", Nil),
    Engram("Thatch Foundation", 3, 2, "", Nil),
    Engram("Thatch Doorframe", 3, 2, "", Nil),
    Engram("Waterskin", 6, 3, "", Nil),
    Engram("Cloth Gloves", 3, 3, "", Nil),
    Engram("Cloth Boots", 3, 3, "", Nil),
    Engram("Cloth Hat", 3, 3, "", Nil),
    Engram("Wooden Sign", 3, 3, "", Nil),
    Engram("Hide Sleeping Bag", 3, 3, "", Nil),
    Engram("Thatch Roof", 3, 3, "", Nil),
    Engram("Thatch Wall", 3, 3, "", Nil),
    Engram("Thatch Door", 3, 3, "", Nil),
    Engram("Slingshot", 6, 5, "", Nil),
    Engram("Storage Box", 6, 5, "", Nil),
    Engram("Simple Bed", 8, 5, "", Nil),
    Engram("Phiomia Saddle", 6, 5, "", Nil),
    Engram("Mortar and Pestle", 6, 5, "", Nil),
    Engram("Sparkpowder", 6, 5, "", Nil),
    Engram("Blood Extraction Syringe", 6, 5, "", Nil),
    Engram("Narcotic", 6, 5, "", Nil),
    Engram("Flag", 6, 5, "", Nil),
    Engram("Standing Torch", 6, 5, "", Nil),
    Engram("Wooden Foundation", 9, 5, "", Nil),
    Engram("Wooden Wall", 9, 5, "", Nil),
    Engram("Paintbrush", 3, 10, "http://hydra-media.cursecdn.com/ark.gamepedia.com/c/c4/Paintbrush.png", Nil),
    Engram("Cooking Pot", 9, 10, "", Nil),
    Engram("Stimulant", 6, 10, "", Nil),
    Engram("Gunpowder", 3, 10, "", Nil),
    Engram("Flare Gun", 6, 10, "", Nil),
    Engram("Spyglass", 6, 10, "", Nil),
    Engram("Small Crop Plot", 9, 10, "", Nil),
    Engram("Parasaur Saddle", 9, 10, "", Nil),
    Engram("Stone Irrigation Pipe - Intake", 6, 10, "", Nil),
    Engram("Stone Irrigation Pipe - Straight", 3, 10, "", Nil),
    Engram("Stone Irrigation Pipe - Tap", 6, 10, "", Nil),
    Engram("Wooden Wall Sign", 3, 10, "", Nil),
    Engram("Wooden Ceiling", 6, 10, "", Nil),
    Engram("Wooden Doorframe", 6, 10, "", Nil),
    Engram("Wooden Door", 6, 10, "", Nil),
    Engram("Wooden Ramp", 3, 10, "", Nil),
    Engram("Hide Pants", 9, 15, "", Nil),
    Engram("Hide Shirt", 6, 15, "", Nil),
    Engram("Bow", 12, 15, "", Nil),
    Engram("Stone Arrow", 3, 15, "", Nil),
    Engram("Large Storage Box", 9, 15, "", Nil),
    Engram("Parachute", 6, 15, "", Nil),
    Engram("Raptor Saddle", 9, 15, "", Nil),
    Engram("Stone Irrigation Pipe - Intersection", 9, 15, "", Nil),
    Engram("Stone Irrigation Pipe - Inclined", 6, 15, "", Nil),
    Engram("Stone Irrigation Pipe - Vertical", 6, 15, "", Nil),
    Engram("Compost Bin", 9, 15, "", Nil),
    Engram("Wooden Billboard", 6, 15, "", Nil),
    Engram("Wooden Fence Foundation", 6, 15, "", Nil),
    Engram("Wooden Pillar", 9, 15, "", Nil),
    Engram("Wooden Hatchframe", 9, 15, "", Nil),
    Engram("Wooden Ladder", 6, 15, "", Nil),
    Engram("Hide Gloves", 9, 20, "", Nil),
    Engram("Hide Boots", 9, 20, "", Nil),
    Engram("Hide Hat", 12, 20, "", Nil),
    Engram("Tranquilizer Arrow", 15, 20, "", Nil),
    Engram("Refining Forge", 21, 20, "", Nil),
    Engram("Trike Saddle", 12, 20, "", Nil),
    Engram("Dinosaur Gateway", 9, 20, "", Nil),
    Engram("Dinosaur Gate", 6, 20, "", Nil),
    Engram("Wooden Catwalk", 12, 20, "", Nil),
    Engram("Wooden Trapdoor", 9, 20, "", Nil),
    Engram("Wooden Windowframe", 12, 20, "", Nil),
    Engram("Preserving Bin", 8, 20, "", Nil)
  )


  val totalEngramEP: Int = (table map ( e => e.points )).sum

  val totalSurvivorEP: Int = levels.values.sum
}
