package net.subfx.arkplanner.js

/**
 * Engram models
 */

case class Engram(id: Int, name: String, points: Int, reqLevel: Int, imageUrl: String, preReqs: List[Engram])

object Engrams {

  val levels: Map[Int, Int] = Map(
    1 -> 0,
    2 -> 8,
    3 -> 8,
    4 -> 8,
    5 -> 8,
    6 -> 8,
    7 -> 8,
    8 -> 8,
    9 -> 8,
    10 -> 12,
    11 -> 12,
    12 -> 12,
    13 -> 12,
    14 -> 12,
    15 -> 12,
    16 -> 12,
    17 -> 12,
    18 -> 12,
    19 -> 12,
    20 -> 16,
    21 -> 16,
    22 -> 16,
    23 -> 16,
    24 -> 16,
    25 -> 16,
    26 -> 16,
    27 -> 16,
    28 -> 16,
    29 -> 16,
    30 -> 20,
    31 -> 20,
    32 -> 20,
    33 -> 20,
    34 -> 20,
    35 -> 20,
    36 -> 20,
    37 -> 20,
    38 -> 20,
    39 -> 20,
    40 -> 24,
    41 -> 24,
    42 -> 24,
    43 -> 24,
    44 -> 24,
    45 -> 24,
    46 -> 24,
    47 -> 24,
    48 -> 24,
    49 -> 24,
    50 -> 28,
    51 -> 28,
    52 -> 28,
    53 -> 28,
    54 -> 28,
    55 -> 28,
    56 -> 28,
    57 -> 28,
    58 -> 28,
    59 -> 28,
    60 -> 40,
    61 -> 40,
    62 -> 40,
    63 -> 40,
    64 -> 40,
    65 -> 1
  )

  val table: List[Engram] = List(
    Engram(1, "Campfire", 3, 2, "http://hydra-media.cursecdn.com/ark.gamepedia.com/0/01/Campfire.png", Nil),
    Engram(2, "Stone Hatchet", 3, 2, "http://hydra-media.cursecdn.com/ark.gamepedia.com/d/d6/Stone_Hatchet.png", Nil),
    Engram(3, "Spear", 3, 2, "http://hydra-media.cursecdn.com/ark.gamepedia.com/4/4f/Spear.png", Nil),
    Engram(4, "Note", 3, 2, "http://hydra-media.cursecdn.com/ark.gamepedia.com/c/cc/Note.png", Nil),
    Engram(5, "Cloth Pants", 3, 2, "http://hydra-media.cursecdn.com/ark.gamepedia.com/6/69/Cloth_Pants.png", Nil),
    Engram(6, "Cloth Shirt", 3, 2, "http://hydra-media.cursecdn.com/ark.gamepedia.com/f/f0/Cloth_Shirt.png", Nil),
    Engram(7, "Thatch Foundation", 3, 2, "http://hydra-media.cursecdn.com/ark.gamepedia.com/4/43/Thatch_Foundation.png", Nil),
    Engram(8, "Thatch Doorframe", 3, 2, "http://hydra-media.cursecdn.com/ark.gamepedia.com/e/e7/Thatch_doorframe.png", Nil),
    Engram(9, "Waterskin", 6, 3, "http://hydra-media.cursecdn.com/ark.gamepedia.com/2/2a/Waterskin_%28Image_2%29.png", Nil),
    Engram(10, "Cloth Gloves", 3, 3, "http://hydra-media.cursecdn.com/ark.gamepedia.com/9/9e/Cloth_Gloves.png", Nil),
    Engram(11, "Cloth Boots", 3, 3, "http://hydra-media.cursecdn.com/ark.gamepedia.com/3/36/Cloth_Boots.png", Nil),
    Engram(12, "Cloth Hat", 3, 3, "http://hydra-media.cursecdn.com/ark.gamepedia.com/4/42/Cloth_Hat.png", Nil),
    Engram(13, "Wooden Sign", 3, 3, "http://hydra-media.cursecdn.com/ark.gamepedia.com/2/22/Wooden_Sign.png", Nil),
    Engram(14, "Hide Sleeping Bag", 3, 3, "http://hydra-media.cursecdn.com/ark.gamepedia.com/e/e8/Hide_Sleeping_Bag.png", Nil),
    Engram(15, "Thatch Roof", 3, 3, "http://hydra-media.cursecdn.com/ark.gamepedia.com/d/da/Thatch_Roof.png", Nil),
    Engram(16, "Thatch Wall", 3, 3, "http://hydra-media.cursecdn.com/ark.gamepedia.com/b/bd/Thatch_Wall.png", Nil),
    Engram(17, "Thatch Door", 3, 3, "http://hydra-media.cursecdn.com/ark.gamepedia.com/0/04/Thatch_door.png", Nil),
    Engram(18, "Slingshot", 6, 5, "http://hydra-media.cursecdn.com/ark.gamepedia.com/3/3f/Slingshot.png", Nil),
    Engram(19, "Storage Box", 6, 5, "http://hydra-media.cursecdn.com/ark.gamepedia.com/d/d0/Storage_Box.png", Nil),
    Engram(20, "Simple Bed", 8, 5, "http://hydra-media.cursecdn.com/ark.gamepedia.com/b/b1/Simple_Bed.png", Nil),
    Engram(21, "Phiomia Saddle", 6, 5, "http://hydra-media.cursecdn.com/ark.gamepedia.com/b/bb/Phiomia_Saddle.png", Nil),
    Engram(22, "Mortar and Pestle", 6, 5, "http://hydra-media.cursecdn.com/ark.gamepedia.com/f/f0/Mortar_And_Pestle.png", Nil),
    Engram(23, "Sparkpowder", 6, 5, "http://hydra-media.cursecdn.com/ark.gamepedia.com/5/56/Sparkpowder.png", Nil),
    Engram(24, "Blood Extraction Syringe", 6, 5, "http://hydra-media.cursecdn.com/ark.gamepedia.com/9/92/Blood_Extraction_Syringe.png", Nil),
    Engram(25, "Narcotic", 6, 5, "http://hydra-media.cursecdn.com/ark.gamepedia.com/e/e6/Narcotic.png", Nil),
    Engram(26, "Flag", 6, 5, "http://hydra-media.cursecdn.com/ark.gamepedia.com/7/76/Flag.png", Nil),
    Engram(27, "Standing Torch", 6, 5, "http://hydra-media.cursecdn.com/ark.gamepedia.com/6/60/Standing_Torch.png", Nil),
    Engram(28, "Wooden Foundation", 9, 5, "http://hydra-media.cursecdn.com/ark.gamepedia.com/f/fb/Wooden_Foundation.png", Nil),
    Engram(29, "Wooden Wall", 9, 5, "http://hydra-media.cursecdn.com/ark.gamepedia.com/0/08/Wooden_Wall.png", Nil),
    Engram(30, "Paintbrush", 3, 10, "http://hydra-media.cursecdn.com/ark.gamepedia.com/c/c4/Paintbrush.png", Nil),
    Engram(31, "Cooking Pot", 9, 10, "http://hydra-media.cursecdn.com/ark.gamepedia.com/f/f9/Cooking_Pot.png", Nil),
    Engram(32, "Stimulant", 6, 10, "http://hydra-media.cursecdn.com/ark.gamepedia.com/e/e2/Stimulant.png", Nil),
    Engram(33, "Gunpowder", 3, 10, "http://hydra-media.cursecdn.com/ark.gamepedia.com/a/ae/Gunpowder.png", Nil),
    Engram(34, "Flare Gun", 6, 10, "http://hydra-media.cursecdn.com/ark.gamepedia.com/5/57/Flare_Gun.png", Nil),
    Engram(35, "Spyglass", 6, 10, "http://hydra-media.cursecdn.com/ark.gamepedia.com/c/c1/Spyglass.png", Nil),
    Engram(36, "Small Crop Plot", 9, 10, "http://hydra-media.cursecdn.com/ark.gamepedia.com/5/59/Small_Crop_Plot.png", Nil),
    Engram(37, "Parasaur Saddle", 9, 10, "http://hydra-media.cursecdn.com/ark.gamepedia.com/b/b6/Parasaur_Saddle.png", Nil),
    Engram(38, "Stone Irrigation Pipe - Intake", 6, 10, "http://hydra-media.cursecdn.com/ark.gamepedia.com/0/0d/Stone_Irrigation_Pipe_Intake.png", Nil),
    Engram(39, "Stone Irrigation Pipe - Straight", 3, 10, "http://hydra-media.cursecdn.com/ark.gamepedia.com/a/a3/Stone_Irrigation_Pipe_Straight.png", Nil),
    Engram(40, "Stone Irrigation Pipe - Tap", 6, 10, "http://hydra-media.cursecdn.com/ark.gamepedia.com/c/c9/Stone_Irrigation_Pipe_Tap.png", Nil),
    Engram(41, "Wooden Wall Sign", 3, 10, "", Nil),
    Engram(42, "Wooden Ceiling", 6, 10, "", Nil),
    Engram(43, "Wooden Doorframe", 6, 10, "", Nil),
    Engram(44, "Wooden Door", 6, 10, "", Nil),
    Engram(45, "Wooden Ramp", 3, 10, "", Nil),
    Engram(46, "Hide Pants", 9, 15, "", Nil),
    Engram(47, "Hide Shirt", 6, 15, "", Nil),
    Engram(48, "Bow", 12, 15, "", Nil),
    Engram(49, "Stone Arrow", 3, 15, "", Nil),
    Engram(50, "Large Storage Box", 9, 15, "", Nil),
    Engram(51, "Parachute", 6, 15, "", Nil),
    Engram(52, "Raptor Saddle", 9, 15, "", Nil),
    Engram(53, "Stone Irrigation Pipe - Intersection", 9, 15, "", Nil),
    Engram(54, "Stone Irrigation Pipe - Inclined", 6, 15, "", Nil),
    Engram(55, "Stone Irrigation Pipe - Vertical", 6, 15, "", Nil),
    Engram(56, "Compost Bin", 9, 15, "", Nil),
    Engram(57, "Wooden Billboard", 6, 15, "", Nil),
    Engram(58, "Wooden Fence Foundation", 6, 15, "", Nil),
    Engram(59, "Wooden Pillar", 9, 15, "", Nil),
    Engram(60, "Wooden Hatchframe", 9, 15, "", Nil),
    Engram(61, "Wooden Ladder", 6, 15, "", Nil),
    Engram(62, "Hide Gloves", 9, 20, "", Nil),
    Engram(63, "Hide Boots", 9, 20, "", Nil),
    Engram(64, "Hide Hat", 12, 20, "", Nil),
    Engram(65, "Tranquilizer Arrow", 15, 20, "", Nil),
    Engram(66, "Refining Forge", 21, 20, "", Nil),
    Engram(67, "Trike Saddle", 12, 20, "", Nil),
    Engram(68, "Dinosaur Gateway", 9, 20, "", Nil),
    Engram(69, "Dinosaur Gate", 6, 20, "", Nil),
    Engram(70, "Wooden Catwalk", 12, 20, "", Nil),
    Engram(71, "Wooden Trapdoor", 9, 20, "", Nil),
    Engram(72, "Wooden Windowframe", 12, 20, "", Nil),
    Engram(73, "Preserving Bin", 8, 20, "", Nil),
    Engram(74, "Smithy", 16, 25, "", Nil),
    Engram(75, "Metal Pick", 12, 25, "", Nil),
    Engram(76, "Metal Hatchet", 12, 25, "", Nil),
    Engram(77, "Pike", 18, 25, "", Nil),
    Engram(78, "Compass", 16, 25, "", Nil),
    Engram(79, "Pulmonoscorpius Saddle", 12, 25, "", Nil),
    Engram(80, "Carbonemys Saddle", 12, 25, "", Nil),
    Engram(81, "Medium Crop Plot", 12, 25, "", Nil),
    Engram(82, "Cementing Paste", 3, 25, "", Nil),
    Engram(83, "Water Tank", 7, 25, "", Nil),
    Engram(84, "Metal Sign", 15, 25, "", Nil),
    Engram(85, "Wooden Window", 12, 25, "", Nil),
    Engram(86, "Metal Spike Wall", 11, 25, "", Nil),
    Engram(87, "Chitin Leggings", 15, 30, "", Nil),
    Engram(88, "Chitin Chestpeice", 18, 30, "", Nil),
    Engram(89, "Chitin Helmet", 18, 30, "", Nil),
    Engram(90, "Water Jar", 12, 30, "", Nil),
    Engram(91, "Simple Pistol", 15, 30, "", Nil),
    Engram(92, "Scope Attachment", 13, 30, "", Nil),
    Engram(93, "Simple Bullet", 6, 30, "", Nil),
    Engram(94, "Stego Saddle", 15, 30, "", Nil),
    Engram(95, "Metal Wall Sign", 6, 30, "", Nil),
    Engram(96, "Metal Foundation", 24, 30, "", Nil),
    Engram(97, "Metal Wall", 15, 30, "", Nil),
    Engram(98, "Metal Doorframe", 24, 30, "", Nil),
    Engram(99, "Grenade", 20, 30, "", Nil),
    Engram(100, "Chitin Gauntlets", 15, 35, "", Nil),
    Engram(101, "Chitin Boots", 15, 35, "", Nil),
    Engram(102, "Longneck Rifle", 18, 35, "", Nil),
    Engram(103, "Simple Rifle Ammo", 6, 35, "", Nil),
    Engram(104, "Large Crop Plot", 15, 35, "", Nil),
    Engram(105, "Pteranodon Saddle", 15, 35, "", Nil),
    Engram(106, "Sarco Saddle", 15, 35, "", Nil),
    Engram(107, "Shotgun", 18, 35, "", Nil),
    Engram(108, "Simple Shotgun Ammo", 6, 35, "", Nil),
    Engram(109, "Metal Pillar", 18, 35, "", Nil),
    Engram(110, "Metal Ceiling", 15, 35, "", Nil),
    Engram(111, "Metal Door", 12, 35, "", Nil),
    Engram(112, "Metal Ramp", 12, 35, "", Nil),
    Engram(113, "Fabricator", 24, 40, "", Nil),
    Engram(114, "Silencer Attachment", 13, 40, "", Nil),
    Engram(115, "Ankylo Saddle", 18, 40, "", Nil),
    Engram(116, "Mammoth Saddle", 18, 40, "", Nil),
    Engram(117, "Metal Irrigation Pipe - Tap", 15, 40, "", Nil),
    Engram(118, "Metal Irrigation Pipe - Straight", 12, 40, "", Nil),
    Engram(119, "Metal Hatchframe", 18, 40, "", Nil),
    Engram(120, "Metal Trapdoor", 14, 40, "", Nil),
    Engram(121, "Metal Fence Foundation", 12, 40, "", Nil),
    Engram(122, "Metal Dinosaur Gateway", 12, 40, "", Nil),
    Engram(123, "Metal Dinosaur Gate", 8, 40, "", Nil),
    Engram(124, "Polymer", 6, 40, "", Nil),
    Engram(125, "Electronics", 6, 40, "", Nil),
    Engram(126, "Flak Leggings", 15, 45, "", Nil),
    Engram(127, "Flak Chestpiece", 18, 45, "", Nil),
    Engram(128, "Improvised Explosive Device", 30, 45, "", Nil),
    Engram(129, "Metal Irrigation Pipe - Intersection", 18, 45, "", Nil),
    Engram(130, "Metal Irrigation Pipe - Inclined", 12, 45, "", Nil),
    Engram(131, "Metal Irrigation Pipe - Vertical", 12, 45, "", Nil),
    Engram(132, "Metal Irrigation Pipe - Tap", 18, 45, "", Nil),
    Engram(133, "Megalodon Saddle", 18, 45, "", Nil),
    Engram(134, "Sabertooth Saddle", 18, 45, "", Nil),
    Engram(135, "Metal Windowframe", 18, 45, "", Nil),
    Engram(136, "Metal Ladder", 21, 45, "", Nil),
    Engram(137, "Flashlight Attachment", 18, 45, "", Nil),
    Engram(138, "GPS", 21, 45, "", Nil),
    Engram(139, "Flak Boots", 16, 50, "", Nil),
    Engram(140, "Flak Gauntlets", 16, 50, "", Nil),
    Engram(141, "Flak Helmet", 20, 50, "", Nil),
    Engram(142, "Metal Billboard", 15, 50, "", Nil),
    Engram(143, "Metal Window", 18, 50, "", Nil),
    Engram(144, "Metal Catwalk", 18, 50, "", Nil),
    Engram(145, "Carno Saddle", 21, 50, "", Nil),
    Engram(146, "Electrical Generator", 24, 50, "", Nil),
    Engram(147, "Straight Electrical Cable", 16, 50, "", Nil),
    Engram(148, "Electrical Outlet", 16, 50, "", Nil),
    Engram(149, "Fabricated Pistol", 16, 50, "", Nil),
    Engram(150, "Advanced Bullet", 18, 50, "", Nil),
    Engram(151, "Remote Keypad", 18, 50, "", Nil),
    Engram(152, "Lamppost", 20, 50, "", Nil),
    Engram(153, "Inclined Electrical Cable", 16, 55, "", Nil),
    Engram(154, "Vertical Electrical Cable", 16, 55, "", Nil),
    Engram(155, "Electrical Cable Intersection", 24, 55, "", Nil),
    Engram(156, "Argentavis Saddle", 21, 55, "", Nil),
    Engram(157, "Bronto Saddle", 21, 55, "", Nil),
    Engram(158, "Refrigerator", 20, 55, "", Nil),
    Engram(159, "Air Conditioner", 21, 55, "", Nil),
    Engram(160, "C4 Remote Detonator", 24, 55, "", Nil),
    Engram(161, "C4 Charge", 12, 55, "", Nil),
    Engram(162, "Assault Rifle", 24, 55, "", Nil),
    Engram(163, "Advanced Rifle Bullet", 8, 55, "", Nil),
    Engram(164, "Laser Attachment", 24, 55, "", Nil),
    Engram(165, "Holo-Scope Attachment", 24, 55, "", Nil),
    Engram(166, "Behemoth Gateway", 28, 55, "", Nil),
    Engram(167, "Behemoth Gate", 15, 55, "", Nil),
    Engram(168, "Rex Saddle", 40, 60, "http://hydra-media.cursecdn.com/ark.gamepedia.com/a/af/Tyrannosaurus_saddle.png", Nil),
    Engram(169, "Spino Saddle", 40, 60, "", Nil),
    Engram(170, "Rocket Launcher", 32, 60, "http://hydra-media.cursecdn.com/ark.gamepedia.com/0/05/Rocket_Launcher.png", Nil),
    Engram(171, "Rocket Propelled Grenade", 8, 60, "http://hydra-media.cursecdn.com/ark.gamepedia.com/9/9e/Rocket_Propelled_Grenade.png", Nil),
    Engram(172, "Auto Turret", 40, 60, "http://hydra-media.cursecdn.com/ark.gamepedia.com/f/f9/Auto_Turret.png", Nil)
  )

  def engramById(id: Int): Option[Engram] = table find (e => e.id == id)

  val totalEngramEP: Int = (table map ( e => e.points )).sum

  val totalSurvivorEP: Int = levels.values.sum
}
